[server]
name = "sky0cloud.dpdns.org"
hostname = "sky0cloud.dpdns.org"
port = 6167

[registration]
enabled = true
guest_enabled = false
token = "only_us"

[security]
trusted_reverse_proxies = ["127.0.0.1", "::1"]

[rooms]
autojoin = ["#info:sky0cloud.dpdns.org", "#idk:sky0cloud.dpdns.org"]
